---
- name: restart check_mk
  systemd:
    name: check_mk@service
    state: restarted

- name: Restart snmpd
  service:
    name: snmpd
    state: restarted

- name: Reload snmpd
  systemd:
    name: snmpd
    state: reloaded
    daemon_reload: true
